apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    editable: true
    jsonData:
      defaultDatabase: pipeline
      server: clickhouse
      port: 8123
      protocol: http
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: demo
